Feature order items as web
EyeSeeTea/dhis2-android-dashboard pull request #27
Opened 2017-07-05 10:11 UTC by manuelplazaspalacio

Close #12

2017-07-10 08:51 UTC, xurxodev requested changes

2017-07-10 08:51 UTC, xurxodev commented on api/src/main/java/org/hisp/dhis/android/dashboard/api/utils/DbUtils.java
> -            // if the last updated field in up to date model is after the same
In general, all code has a sense for me but I have doubts with this removed code, can you explain to me because this code must be removed?

2017-07-10 09:37 UTC, manuelplazaspalacio commented on api/src/main/java/org/hisp/dhis/android/dashboard/api/utils/DbUtils.java
> -            // if the last updated field in up to date model is after the same
If this code still there, only saves the dashboard items that have the updated date before the last updated date. The problem with this is when I update the order of all the dashboard items of a dashboard when reach to here it only saves da order of the new item added. For example if I have 3 items with order 0,1,2 then I add a new one I put the order to the items 0,1,2,3 but then when comes to here only saves the new one, the position saved will be 0,0,1,2.

2017-07-11 04:59 UTC, xurxodev approved these changes
thanks @manuelplazaspalacio

2017-07-11 04:59 UTC, merged