Feature add unit test
EyeSeeTea/dhis2-android-dashboard pull request #4
Opened 2017-05-05 16:59 UTC by idelcano

Closes #2

2017-05-08 11:06 UTC, xurxodev requested changes
@idelcano I have request you some changes, can you review it please?

2017-05-08 11:06 UTC, xurxodev commented on api/src/test/java/org/hisp/dhis/android/core/PreconditionsTests.java
> +package org.hisp.dhis.android.core;
@idelcano package is not correct, package should be org.hisp.dhis.android.dashboard.api, can you refactor for all unit tests?

2017-05-08 11:06 UTC, xurxodev commented on api/src/test/java/org/hisp/dhis/android/core/api/BasicAuthenticatorTests.java
> +// ToDo: Solve problem with INFO logs from MockWebServer being interpreted as errors in gradle
@idelcano execute all unit test is not possible because project not compile for this file, can you review it, please?

2017-05-08 11:06 UTC, xurxodev commented on api/src/test/java/org/hisp/dhis/android/core/converters/AccessConverterTests.java
> +        String access = new FileReader().getStringFromFile("access_all_true_string.txt");
@idelcano Can you refactor duplicate file names to static variables?

2017-05-08 11:06 UTC, xurxodev commented on api/src/test/java/org/hisp/dhis/android/core/converters/AccessConverterTests.java
> +public class AccessConverterTests {
@idelcano Can you add a test for verify provideDefaultAccess method?

2017-05-08 11:06 UTC, xurxodev commented on api/src/test/java/org/hisp/dhis/android/core/converters/AccessConverterTests.java
> +        accessObject = new Access();
@idelcano accessObject is create in setUp method that is invoked before every test but only is used in first test

2017-05-08 11:06 UTC, xurxodev commented on api/src/test/java/org/hisp/dhis/android/core/converters/DateTimeConverterTests.java
> +        dateTime = new DateTime(calendar);
@idelcano dateTime is create in setUp method that is invoked before every test but only is used in second test

2017-05-08 11:06 UTC, xurxodev commented on api/src/test/java/org/hisp/dhis/android/core/dashboard/DashboardTests.java
> +public class DashboardTests {
@idelcano I don´t understand utility of DashboardTests, really you are testing jackson library for deserialization of json files, I think this tests is not necessary.

2017-05-08 11:06 UTC, xurxodev commented on api/src/test/java/org/hisp/dhis/android/core/interpretation/InterpretationTests.java
> +public class InterpretationTests {
@idelcano I don´t understand utility of InterpretationTests, really you are testing jackson library for deserialization of json files, I think this tests is not necessary.

2017-05-08 11:06 UTC, xurxodev commented on api/src/test/java/org/hisp/dhis/android/core/network/ApiExceptionTests.java
> +        APIException apiException = APIException.fromRetrofitError(
@idelcano for all test has same approach can you create a private method to create this apiException?

2017-05-08 11:06 UTC, xurxodev commented on api/src/test/java/org/hisp/dhis/android/core/systeminfo/SystemInfoTests.java
> +public class SystemInfoTests {
@idelcano I don´t understand utility of SystemInfoTests, really you are testing jackson library for deserialization of json files, I think this tests is not necessary.

2017-05-08 11:06 UTC, xurxodev commented on api/src/test/java/org/hisp/dhis/android/core/user/UserTests.java
> +public class UserTests {
@idelcano I don´t understand utility of UserTests, really you are testing jackson library for deserialization of json files, I think this tests is not necessary.

2017-05-08 15:04 UTC, idelcano commented
@xurxodev  done!

2017-05-09 06:45 UTC, xurxodev approved these changes
thanks @idelcano

2017-05-09 06:45 UTC, merged